### ISSUE TITLE
与c#的一个kcp库客户端互相通信出现attempt to add with overflow 报错

### ISSUE THREAD

**Issue by zzlettle** [luyikk/kcp_server#1]
最近在学习开发unity游戏，客户端这边用的是c#的一个kcp库
https://github.com/KumoKyaku/KCP
然后把这个库里面的
TestClient官方代码当作客户端代码运行
发现和rust的这个服务器版本通讯的时候
立马会报错
thread 'tokio-runtime-worker' panicked at \.cargo\registry\src\index.crates.io-6f17d22bba15001f\kcpserver-1.1.3\src\kcp\kcp_module\kcp.rs:482:19:
attempt to add with overflow
发现是update_ack这个方法里面的
let rto = self.rx_srtt + cmp::max(self.interval, 4 * self.rx_rttval);
这句代码有问题
![屏幕截图 2024-06-30 031037](https://github.com/luyikk/kcp_server/assets/7059445/7d4b0e43-bb0e-41e1-be3b-8d8ddbf30e1e)

这个c#的客户端代码与其他的服务器kcp通讯都没有问题
无论是它自己的服务端还是和另外一个rust的kcp库
https://github.com/Matrix-Zhang/tokio_kcp
互相通信都没有问题

**Comment by luyikk** [comment]
我有空看看

**Comment by zzlettle** [comment]
问题好像出在
kcp_listener.rs里面的new方法的
![Image](https://github.com/luyikk/kcp_server/assets/7059445/fc1fc04e-36b6-4c7c-aded-9a23af59d7c8)

里面的kcp_peer.input传递给后面kcp解析的数据data
解析出来的ts特别小，导致了timediff方法计算出来的rtt特别大
然后传递到后面的update_ack方法计算rto的时候超出了u32的范围，溢出panic崩溃

**Comment by luyikk** [comment]
已修复
